openapi: "3.0.0"
info:
  version: 1.0.0
  title: Trade Order API
  license:
    name: Apache 2.0
  description: trade order API
  contact:
    name: Francis Gnanamuthu
paths:
  /trade/orders:
    post:
      summary: Create a trade order
      operationId: createOrder
      tags:
        - trade-order-api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /trade/orders/summary:
    get:
      summary: >-
        Total number of orders, with the total quantity and average price.
        It should also return the total number of combinable orders (see definition below)
      operationId: getSummary
      tags:
        - trade-order-api
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetOrderResponse'
  /trade/orders/security/{security}:
    get:
      summary:  summary for a specified security
      operationId: getOrderBySecurity
      tags:
        - trade-order-api
      parameters:
        - name: security
          in: path
          description: Security Id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetOrderResponse'
  /trade/orders/fund/{fund}:
    get:
      summary:  summary for a specified fund
      operationId: getOrderByFund
      tags:
        - trade-order-api
      parameters:
        - name: fund
          in: path
          description: fund
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetOrderResponse'
components:
  schemas:
    OrderResponse:
      properties:
        orderId:
          type: string
    Order:
      required:
        - side
        - security
        - fund-name
        - quantity
        - price
      properties:
        side:
          type: string
          enum:
            - Buy
            - Sell
          example: "Buy"
        security:
          type: string
          maxLength: 250
          minLength: 1
          example: "AAPL"
        fund-name:
          type: string
          maxLength: 250
          minLength: 1
          example: "MAG"
        quantity:
          type: integer
          format: int64
          maxLength: 100000
          example: 1000
        price:
          type: number
          maxLength: 900000
          example: 700
    GetOrderResponse:
      properties:
        totalNumberOfOrders:
          type: integer
          format: int64
        totalQuantity:
          type: integer
          format: int64
        averagePrice:
          type: number
        combinableOrder:
          type: string
    ErrorResponse:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: integer
          format: int32
          description: A server defined error code that uniquely identifies error
        message:
          type: string
          description: Description of the code
      description: >-
        An object containing more specific information than the current object
        about the error.